name: ROS Pipeline

on:
  schedule:
    - cron: '*/15 15-5 * 9-1 *'   # every 15 min in season
  workflow_dispatch:            # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python export_json.py
      - name: Publish JSON to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public          # export_json writes here
