name: ROS Pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write    # allow push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python scrapers/ffa_projections.py
        continue-on-error: true
      - run: python scrapers/schedule_weights.py
        continue-on-error: true
      - run: python scrapers/usage_sync.py
        continue-on-error: true
      - run: python scrapers/sleeper_players.py
        continue-on-error: true
      - run: python export_json.py
      - name: Commit prev_ros.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/prev_ros.json
          git commit -m "Update prev_ros.json" || echo "No changes"
          git push
      - name: Publish JSON to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
